name: CI

on:
  push:
    branches: [ 1.14 ]
  pull_request:
    branches: [ 1.14 ]
  workflow_dispatch:

jobs:
# run after all other jobs have completed to check overall build status
  discord-notification:
    runs-on: ubuntu-20.04

    name: Discord Notification

    needs: [ubuntu-2004-scons-gcc-release-lto, ubuntu-2004-cmake-clang-debug, translations, macos-intel-debug, macos-intel-release]
    if: always()

    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: rjstone/discord-webhook-notify@v1
        if: env.WORKFLOW_CONCLUSION == 'failure' && github.event_name == 'push'
        with:
          severity: error
          webhookUrl: ${{ secrets.DISCORD_CI_WEBHOOK }}
          description: |-
            pusher: ${{ github.actor }}
            commit: ${{ github.event.head_commit.message }}
            commit url: ${{ github.event.head_commit.url }}

  ubuntu-2004-scons-gcc-release-lto:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Ubuntu 20.04
        run: |
          export BRANCH=master
          export IMAGE=2004
          export NLS=false
          export TOOL=scons
          export CC=gcc
          export CXX=g++
          export CXX_STD=11
          export CFG=release
          export LTO=true
          export CACHE_DIR=/home/wesnoth-CI/build
          ./.github/workflows/ci-scripts/ubuntu.sh

  ubuntu-2004-cmake-clang-debug:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Ubuntu 20.04
        run: |
          export BRANCH=master
          export IMAGE=2004
          export NLS=false
          export TOOL=cmake
          export CC=clang
          export CXX=clang++
          export CXX_STD=11
          export CFG=debug
          export LTO=false
          export CACHE_DIR=/home/wesnoth-CI/build
          ./.github/workflows/ci-scripts/ubuntu.sh

  translations:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Translations
        run: |
          export BRANCH=master
          export IMAGE=2004
          export NLS=only
          export TOOL=scons
          export CC=gcc
          export CXX=g++
          export CXX_STD=11
          export CFG=release
          export LTO=false
          export CACHE_DIR=/home/wesnoth-CI/build
          ./.github/workflows/ci-scripts/ubuntu.sh

  macos-intel-debug:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: macOS Intel Debug
        run: |
          export CFG=Debug
          export CACHE_DIR=~/build-cache
          ./.github/workflows/ci-scripts/macos.sh

  macos-intel-release:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: macOS Intel Release
        run: |
          export CFG=Release
          export CACHE_DIR=~/build-cache
          ./.github/workflows/ci-scripts/macos.sh
